import React from 'react';
import Head from 'next/head'
import {GetStaticPaths, GetStaticProps} from "next";
import {fetch} from "next/dist/compiled/@edge-runtime/primitives/fetch";
import ReactMarkdown from "react-markdown";
import {IPost} from "@/model";
import styles from "@/styles/Post.module.scss"
import Image from "next/image";
import {getDate} from "@/utils";

export const getStaticPaths : GetStaticPaths = async () => {
    const res = await fetch(`https://ug-mern-blog.onrender.com/posts`)
    const {posts} = await res.json()

    const paths = posts.map((post: IPost) => ({
            params: {
                id: post._id.toString()
            }
        })
    )

    return {paths, fallback: false}
}
export const getStaticProps : GetStaticProps = async (context) => {
    const {id}:any = context.params
    const res = await  fetch(`https://ug-mern-blog.onrender.com/posts/${id}`)
    const {doc} = await res.json()

    return {
        props: {post:doc},
        revalidate: 30,
    }
}

const Post = ({post}:{post:IPost}) => {
    return (
        <>
            <Head>
                <title>{post.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className={styles.card}>
                <div className={styles.wrapper_image}>
                    <Image
                        loader={() => `https://ug-mern-blog.onrender.com${post.imageUrl}` }
                        src={`https://ug-mern-blog.onrender.com${post.imageUrl}`}
                        alt={"#"}
                        unoptimized={true}
                        fill
                    />
                </div>
                <h1 className={styles.title}>
                    {post.title}
                </h1>
                <div className={styles.info}>
                   <article className={styles.text}>
                       <ReactMarkdown children={post.text}/>
                   </article>
                    <div className={styles.tags_card}>
                        {post.tags.map((tag:string,index:number)=><span key={index}>#{tag}</span>)}
                    </div>
                    <div className={styles.statistics}>
                        <div className={styles.views}>
                            <svg className="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false"
                                 aria-hidden="true" viewBox="0 0 24 24" data-testid="RemoveRedEyeOutlinedIcon" width={18} height={18}>
                                <path
                                    d="M12 6.5c3.79 0 7.17 2.13 8.82 5.5-1.65 3.37-5.02 5.5-8.82 5.5S4.83 15.37 3.18 12C4.83 8.63 8.21 6.5 12 6.5m0-2C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zm0 5c1.38 0 2.5 1.12 2.5 2.5s-1.12 2.5-2.5 2.5-2.5-1.12-2.5-2.5 1.12-2.5 2.5-2.5m0-2c-2.48 0-4.5 2.02-4.5 4.5s2.02 4.5 4.5 4.5 4.5-2.02 4.5-4.5-2.02-4.5-4.5-4.5z"></path>
                            </svg>
                            <span>
                                    {post.viewsCount}
                                </span>
                        </div>
                    </div>
                    <div className={styles.privat_info}>
                        <div className={styles.author}>
                            <h4>{post.author.fullName}</h4>
                            <div className={styles.avatar}>
                                <Image
                                    loader={() => `https://ug-mern-blog.onrender.com${post.author.avatarUrl}` }
                                    src={`https://ug-mern-blog.onrender.com${post.author.avatarUrl}`}
                                    alt={"#"}
                                    unoptimized={true}
                                    fill
                                />
                            </div>
                        </div>
                        <p>
                            {getDate(post.createdAt)}
                        </p>
                    </div>
                </div>

            </div>
        </>
    );
};

    export default Post;