import React from 'react';
import Head from "next/head";
import styles from "@/styles/Home.module.scss";

const About = () => {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={styles.main}>
                about us
            </main>

        </>
    );
};

export default About;