import React from 'react';
import Head from "next/head";
import styles from "@/styles/About.module.scss";
import {ITechnologies, ITechnology} from "@/model";

export const getStaticProps = async () => {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_HOST}/api/technologies`)
    const data = await res.json()

    return {
        props: {technologies:data},
    }
}

const About = ({technologies}:{technologies:ITechnologies}) => {

    const renderTechnologies  = (technologies: ITechnology[]) => {
        return(
            <ul className={styles.list}>
                {technologies.map((tech)=>(
                    <li key={tech.id} className={styles.item}>
                        <a href={tech.link} target="_blank" rel="noreferrer">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="25px" height="25px"><path d="M 25 2 C 12.317 2 2 12.317 2 25 C 2 37.683 12.317 48 25 48 C 37.683 48 48 37.683 48 25 C 48 20.44 46.660281 16.189328 44.363281 12.611328 L 42.994141 14.228516 C 44.889141 17.382516 46 21.06 46 25 C 46 36.579 36.579 46 25 46 C 13.421 46 4 36.579 4 25 C 4 13.421 13.421 4 25 4 C 30.443 4 35.393906 6.0997656 39.128906 9.5097656 L 40.4375 7.9648438 C 36.3525 4.2598437 30.935 2 25 2 z M 43.236328 7.7539062 L 23.914062 30.554688 L 15.78125 22.96875 L 14.417969 24.431641 L 24.083984 33.447266 L 44.763672 9.046875 L 43.236328 7.7539062 z"/></svg>
                            <span>
                                {tech.name}
                            </span>
                        </a>
                    </li>
                ))}
            </ul>
        )
    }
    const renderGitHubLink = (link:string) => {
        return(
            <div className={styles.github_link}>
                <a href={link} rel="noreferrer">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" width="40px" height="40px"><path d="M15,3C8.373,3,3,8.373,3,15c0,5.623,3.872,10.328,9.092,11.63C12.036,26.468,12,26.28,12,26.047v-2.051 c-0.487,0-1.303,0-1.508,0c-0.821,0-1.551-0.353-1.905-1.009c-0.393-0.729-0.461-1.844-1.435-2.526 c-0.289-0.227-0.069-0.486,0.264-0.451c0.615,0.174,1.125,0.596,1.605,1.222c0.478,0.627,0.703,0.769,1.596,0.769 c0.433,0,1.081-0.025,1.691-0.121c0.328-0.833,0.895-1.6,1.588-1.962c-3.996-0.411-5.903-2.399-5.903-5.098 c0-1.162,0.495-2.286,1.336-3.233C9.053,10.647,8.706,8.73,9.435,8c1.798,0,2.885,1.166,3.146,1.481C13.477,9.174,14.461,9,15.495,9 c1.036,0,2.024,0.174,2.922,0.483C18.675,9.17,19.763,8,21.565,8c0.732,0.731,0.381,2.656,0.102,3.594 c0.836,0.945,1.328,2.066,1.328,3.226c0,2.697-1.904,4.684-5.894,5.097C18.199,20.49,19,22.1,19,23.313v2.734 c0,0.104-0.023,0.179-0.035,0.268C23.641,24.676,27,20.236,27,15C27,8.373,21.627,3,15,3z"></path></svg>
                </a>
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={styles.main}>
                <article className={styles.article}>
                    Hello everyone. This is one of my pet projects blog site where you can leave your posts and comments on them .
                    Below is a list of technologies used to create the site.
                </article>
                <div className={styles.technologies_wrapper}>
                    <div className={styles.technologies}>
                        <h3>
                            Backend:
                        </h3>
                        {renderTechnologies(technologies.backend.technologies)}
                        {renderGitHubLink(technologies.backend.gitHubLink)}
                    </div>
                    <div className={styles.technologies} >
                        <h3>
                            Frontend:
                        </h3>
                        {renderTechnologies(technologies.frontend.technologies)}
                        {renderGitHubLink(technologies.frontend.gitHubLink)}
                    </div>
                </div>
            </main>

        </>
    );
};

export default About;