import React, {useEffect, useState} from 'react';
import Head from "next/head";
import styles from "@/styles/AddPost.module.scss";
import PostForm from "@/components/post-form";
import {ICreatedPost, ICreatedPostResponse} from "@/model";
import {useAppSelector} from "@/hook";
import {useRouter} from "next/router";
import {useCreatePostMutation} from "@/store/postApi";


const AddPost = () => {
    const [textMarkdown, setTextMarkdown] = useState("");
    const  router = useRouter()
    const [createPost] = useCreatePostMutation();
    const auth = useAppSelector((state) => state.auth.value)
    useEffect(()=>{
        if(!auth)router.push('/login')
    },[auth])
    const submitHandle = async (values: ICreatedPost) =>{
        if(window.confirm("Create post?")){
            const {data}:{data:ICreatedPostResponse} | any = await createPost({...values})
            !!data.success && router.push(`/`)

        }
    }
    return (
        <>
            <Head>
                <title>Add post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={styles.main}>
                <PostForm textMarkdown={textMarkdown} setTextMarkdown={setTextMarkdown} submitHandle={submitHandle}/>
            </main>

        </>
    );
};

export default AddPost;