import React,{useState} from 'react';
import Head from "next/head";
import styles from "@/styles/AddPost.module.scss";
import PostForm from "@/components/post-form";
import {ICreatedPost} from "@/model";


const AddPost = () => {
    const [textMarkdown, setTextMarkdown] = useState("");
    const submitHandle = (values: ICreatedPost) =>{
        console.log(values)
    }
    return (
        <>
            <Head>
                <title>Add post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={styles.main}>
                <PostForm textMarkdown={textMarkdown} setTextMarkdown={setTextMarkdown} submitHandle={submitHandle}/>
            </main>

        </>
    );
};

export default AddPost;