import React, {useEffect} from 'react';
import Head from "next/head";
import { Formik } from 'formik';
import styles from "@/styles/LoginRegister.module.scss";
import {useFetchAuthMutation} from "@/store/authApi";
import {ISignIn, ISignInResponse} from "@/model";
import {useRouter} from "next/router";
import {setAuthState} from "@/store/slice/authSlice";
import {useAppDispatch, useAppSelector} from "@/hook";


const Login = () => {
    const  router = useRouter()
    const dispatch = useAppDispatch()
    const [fetchAuth, result] = useFetchAuthMutation()
    const theme = useAppSelector(state => state.theme.value)

    const auth = useAppSelector((state) => state.auth.value)
    useEffect(()=>{
        if(auth)router.push('/')
    },[auth])


    const submitHandle = async (values:ISignIn) => {
        // @ts-ignore
        const {data} : {data:ISignInResponse | undefined } = await (fetchAuth(values))
        if(!data){
            return alert('Failed to sign in')
        }
        if('token' in data){
            window.localStorage.setItem('token', data.token);
            dispatch(setAuthState(true))
        }
        router.push('/')
    }

    return (
        <>
            <Head>
                <title>Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className={`${styles.main} ${theme==='dark' ? styles.main_dark : ''}`}>
                <h2>Sign in</h2>
                <div className={styles.wrapper}>
                    <Formik
                        initialValues={{ email: '', password: '' }}
                        validate={values => {
                            const errors:any = {};
                            if (!values.email) {
                                errors.email = 'Required';
                            } else if (
                                !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(values.email)
                            ) {
                                errors.email = 'Invalid email address';
                            }

                            if(!values.password){
                                errors.password = 'Required';
                            }
                            return errors;
                        }}
                        onSubmit={async (values, { setSubmitting }) => {
                            await submitHandle(values)
                            values.email = ''
                            values.password= ''

                        }}
                    >
                        {({
                              values,
                              errors,
                              touched,
                              handleChange,
                              handleBlur,
                              handleSubmit,
                              isSubmitting,
                              /* and other goodies */
                          }) => (
                            <form className={styles.form} onSubmit={handleSubmit}>
                                <input
                                    type="email"
                                    name="email"
                                    placeholder="email"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.email}
                                    className={`${styles.input} ${theme==='dark' ? styles.input_dark : ''}`}
                                />
                                {errors.email && touched.email && <div className={styles.input_error}>
                                    {errors.email}
                                </div>}
                                <input
                                    type="password"
                                    name="password"
                                    placeholder="password"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.password}
                                    className={`${styles.input} ${theme==='dark' ? styles.input_dark : ''}`}
                                />
                                {errors.password && touched.password && <div className={styles.input_error}>
                                    {errors.password}
                                </div>}
                                <button type="submit"  className={`${styles.button} ${theme==='dark' ? styles.button_dark : ''}`}>
                                    Submit
                                </button>
                            </form>
                        )}
                    </Formik>
                </div>
            </div>
        </>
    );
};

export default Login;