import React from 'react';
import Head from "next/head";
import styles from "@/styles/Login.module.scss";

const Login = () => {
    return (
        <>
            <Head>
                <title>Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={styles.main}>
                <div>

                </div>
            </main>
        </>
    );
};

export default Login;